site_name: PyLGEN

nav:
  - Overview: index.md
  - Meeting PyLGEN:
    - Quick Start: section-1/quick_start.md
    - Example 1: 
      - Introduction: section-1/example-1-first-approach.md
      - Step 1 (Lexical Analysis): section-1/example-1-step-1.md
      - Step 2 (Syntax Analysis): section-1/example-1-step-2.md

theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate
    - navigation.footer
    - content.code.copy

  palette:
    
    - scheme: default
      primary: 'teal'
      accent: 'amber'
      toggle:
        icon: material/brightness-7
        name: dark mode

    - scheme: slate
      primary: 'teal'
      accent: 'amber'
      toggle:
        icon: material/brightness-4
        name: light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences