site_name: PyLGEN

nav:
  - Overview: index.md
  - Meeting PyLGEN:
    - Quick Start: section-1/quick_start.md
    - Example 1: 
      - Introduction: section-1/example-1-first-approach.md
      - Step 1 (Lexical Analysis): section-1/example-1-step-1.md
      - Step 2 (Syntax Analysis): section-1/example-1-step-2.md
      - Pause and Reflect (Visualizing Our Progress): section-1/example-1-pause-and-reflect.md
      - Step 3 (Semantic Analysis): section-1/example-1-step-3.md
      - Step 4 (The Final Step): section-1/example-1-step-4.md
    - From Prototype to Production:
      - Introduction: benchmark/benchmark-intro.md
      - Getting to know VecLang: benchmark/getting-to-know-veclang.md
      - Step 1: benchmark/step-1.md
      - Step 2: benchmark/step-2.md
      - Step 3: benchmark/step-3.md
      - Language Evolution: benchmark/from-arithmetic-to-veclang.md
      - Step 4: benchmark/step-4.md
      - Benchmark: benchmark/benchmark-conclusion.md
    - A Practical Tour for PyLGEN Framework:
      - Introduction: api/intro.md
      - Common Module: api/common/common.md
      - Automaton Module:
        - The Engine of Pattern Matching: api/automaton/intro.md
        - Automata Theory: api/automaton/theory.md
        - The Theory in Action: api/automaton/automaton.md
      - Grammar Module:
        - The Syntactic Blueprint: api/grammar/intro.md
        - The Formal Foundation: api/grammar/theory.md
        - From Theory to Implementation: api/grammar/grammar.md
      - Regex Module: api/regex/regex.md
      - Lexer Module: api/lexer/lexer.md
      - Parser Module: api/parser/parser.md
      - Analysis Module: api/analysis/analysis.md
      - Visual Module (Bonus): api/visual/visual.md

theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate
    - navigation.footer
    - content.code.copy

  palette:
    
    - scheme: default
      primary: 'teal'
      accent: 'amber'
      toggle:
        icon: material/brightness-7
        name: dark mode

    - scheme: slate
      primary: 'teal'
      accent: 'amber'
      toggle:
        icon: material/brightness-4
        name: light mode

markdown_extensions:
  - pymdownx.highlight:
        use_pygments: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

extra_css:
    - stylesheets/extra.css
    - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js