from hashlib import sha256
from typing import Any, Dict, List, Set, Tuple
from common.table import Table

class State:

    def __init__(self,id: str,value: Any,is_accept:bool=False): ...

    @property
    def id(self) -> str: ...

    @property
    def value(self) -> Any: ...
    
    @property
    def is_accept(self) -> bool:...
    
    def __str__(self) -> str: ...
    
    def __repr__(self) -> str: ...
    
    def __eq__(self, __o: object) -> bool: ...
    
    def __hash__(self) -> int: ...

class Automaton:
    '''
    Base class for automaton definition
    '''
    
    @property
    def id(self) -> str: ...

    @property
    def alphabet(self) -> Set[str]: ...
    
    @property
    def start_state(self) -> State: ...
    
    @property
    def current_state(self) -> State: ...
    
    @property
    def states(self) -> Set[State]: ...
    
    @property
    def finals(self) -> Set[State]: ...
    
    @property
    def is_complete(self) -> bool: ...
    
    @property
    def transition_function(self) -> Dict[Tuple[str,str],str]: ...

    @staticmethod
    def Union(automatons:Set[Automaton]) -> NFA: ...

    @staticmethod
    def Complement(automaton:Automaton) -> DFA: ...
    
    def add_transition(self,from_state:State,to_state: State,symbol: str) -> None: ...
    
    def has_transition(self,state: State,symbol: str) -> bool: ...

    def next(self,state: State,symbol: str) -> State: ...
    
    def reset(self) -> None: ...
    
    def clousure(self,state: State) -> Set[State]: ...
    
    def make_complete(self) -> None: ...

    def restore_to_before_complete(self) -> None: ...

class DFA(Automaton):

    def __init__(
        self,
        start_id: str,
        start_value: Any,
        alphabet: Set[str],
        start_accept:bool=False
    ): ...
    
    def walk(self,symbol:str) -> None: ...
    
    def accept(self,string: List[str]) -> bool: ...

    def minimize(self) -> DFA: ...

    def __iadd__(self,transition:Tuple[State,str,State] ) -> DFA: ...

class NFA(Automaton):
    
    def __init__(
        self,
        start_id: str,
        start_value:Any,
        alphabet:Set[str],
        start_accept:bool=False
    ): ...

    def add_epsilon_transition(self,from_state:State,to_state:State) -> None: ...
    
    def to_deterministic(self) -> DFA: ...

    def __iadd__(self,transition:Tuple[State,str,State]) -> NFA: ...

def create_dfa(states:Set[State],transition_function:Table,start_id:str,alphabet:Set[str]) -> DFA: ...