from hashlib import sha256
from typing import Any

class State:

    def __init__(self,id: str,value: Any,is_accept:bool=False): ...

    @property
    def id(self) -> str: ...

    @property
    def value(self) -> Any: ...
    
    @property
    def is_accept(self) -> bool:...
    
    def __str__(self) -> str: ...
    
    def __repr__(self) -> str: ...
    
    def __eq__(self, __o: object) -> bool: ...
    
    def __hash__(self) -> int: ...