from typing import List, Set

from .enums import TokenType,ErrorType

class Symbol:

    def __init__(self,symbol:str,is_terminal:bool = False,is_epsilon:bool = False): ...
    
    @property
    def symbol(self) -> str: ...
    
    @property
    def is_terminal(self) -> bool: ...
    
    @property
    def is_epsilon(self) -> bool: ...
    
    def __str__(self) -> str: ...
    
    def __repr__(self) -> str: ...

    def __eq__(self, other) -> bool: ...

    def __hash__(self) -> int: ...

class AST:
    '''
    Abstract Syntax Tree class
    '''
    def __init__(self,symbol:Symbol,line:int,column:int): ...
    
    @property
    def symbol(self) -> Symbol: ...
    
    @property
    def line(self) -> int: ...
    
    @property
    def column(self) -> int: ...

    @property
    def is_error(self) -> bool: ...

    def children(self) -> List[AST]: ...

    def __str__(self) -> str: ...
    
    def __repr__(self) -> str: ...

from typing import List


class Error:

    def __init__(self,type_:ErrorType,line:int,column:int,msg:str) -> None: ...
    
    @property
    def line(self) -> int: ...

    @property
    def column(self) -> int: ...
    
    @property
    def type(self) -> ErrorType: ...

    @property
    def message(self) -> str: ...

    def __str__(self) -> str: ...
    
    def __repr__(self) -> str: ...

    def __hash__(self) -> int: ...
    
    def __eq__(self, __o: object) -> bool: ...

class LexicalError(Error):

    def __init__(self, msg:str, line:int, column:int) -> None: ...

class SyntaxError(Error):

    def __init__(self, msg:str ,line:int, column:int) -> None: ...

class SemanticError(Error):

    def __init__(self, msg:str,line:int, column:int) -> None: ...

class RuntimeError(Error):

    def __init__(self,stack_trace:List[str], line:int, column:int, msg:str) -> None: ...

    @property
    def stack_trace(self) -> List[str]: ...

class ErrorAST(AST):

    def __init__(self, symbol:Symbol, line:int, column:int,errors:Set[SemanticError]): ...

class ASTListView:

    def __getitem__(self,idx:int) -> AST: ...

    def __len__(self) -> int: ...

class Token(AST):

    def __init__(self,text:str, type_:TokenType, symbol: Symbol, line: int, column: int): ...    
    
    @property
    def text(self) -> str: ...
    
    @property
    def type(self) -> TokenType: ...