from hashlib import sha256
from typing import Any, List, Set, Tuple
from .enums import TokenType,ErrorType

class Symbol:
    '''
    Class that represents a grammar symbol
    '''

    def __init__(self,symbol:str,is_terminal:bool = False,is_epsilon:bool = False): ...
    
    @property
    def symbol(self) -> str: ...
    
    @property
    def is_terminal(self) -> bool: ...
    
    @property
    def is_epsilon(self) -> bool: ...
    
    def __str__(self) -> str: ...
    
    def __repr__(self) -> str: ...
    
    def __eq__(self,other) -> bool: ...
    
    def __hash__(self) -> int: ...

class AST:
    '''
    Abstract Syntax Tree class
    '''
    def __init__(self,symbol:Symbol,start_line:int,start_column:int,end_line:int,end_column:int): ...
    
    @property
    def symbol(self) -> Symbol: ...
    
    @property
    def start_position(self) -> Tuple[int,int]: ...
    
    @property
    def end_position(self) -> Tuple[int,int]: ...
    
    @property
    def is_error(self) -> bool: ...
    
    def children(self) -> List[AST]: ...
    
    def __str__(self) -> str: ...
    
    def __repr__(self) -> str: ...

class Error:

    def __init__(self,type_:ErrorType,start_line:int,start_column:int,end_line:int,end_column:int,msg:str): ...
    
    @property
    def start_position(self) -> Tuple[int,int]: ...

    @property
    def end_position(self) -> Tuple[int,int]: ...
    
    @property
    def type(self) -> ErrorType: ...
    
    @property
    def message(self) -> str: ...
    
    def __str__(self) -> str: ...
    
    def __repr__(self) -> str: ...
    
    def __hash__(self) -> int: ...
    
    def __eq__(self, __o: object) -> bool: ...

class LexicalError(Error):

    def __init__(self,msg:str,start_line:int,start_column:int,end_line:int,end_column:int): ...

class SyntaxError(Error):

    def __init__(self,msg:str,start_line:int,start_column:int,end_line:int,end_column:int): ...

class SemanticError(Error):

    def __init__(self,msg:str,start_line:int,start_column:int,end_line:int,end_column:int): ...

class RuntimeError(Error):

    def __init__(self,stack_trace:List[str],start_line:int,start_column:int,end_line:int,end_column:int,msg:str): ...    

    @property
    def stack_trace(self) -> List[str]: ...

class ErrorAST(AST):
    '''
    Error Syntax Tree Class
    '''
    def __init__(self,symbol:Symbol,start_line:int,start_column:int,end_line:int,end_column:int,errors:Set[SemanticError] ): ...

class ASTListView:

    def __getitem__(self, idx:int) -> AST: ...

    def __len__(self) -> int: ...

class Token(AST):

    def __init__(self,text:str, type_:Any, symbol:Symbol,line:int,column:int): ...    

    def children(self) -> List[AST]:
        return []

    @property
    def text(self) -> str: ...
    
    @property
    def type(self) -> Any: ...