from typing import List, Set, Tuple

from common.types import Symbol

class Production:

    def __init__(self,head:Symbol,production:List[Symbol]): ...
    
    @property
    def id(self) -> str: ...
    
    @property
    def head(self) -> Symbol: ...
    
    @property
    def production(self) -> List[Symbol]: ...
    
    def __str__(self) -> str: ...
    
    def __repr__(self) -> str: ...
    
    def __eq__(self, o) -> bool: ...
    
    def __hash__(self) -> int: ...

class ProductionsSet:

    def __init__(self): ...
    
    @property
    def productions(self) -> List[List[Symbol]]: ...
    
    def __iadd__(self,production:Tuple[Symbol,...]) -> ProductionsSet: ...

class Grammar:

    def __init__(self,start_symbol:Symbol,end_symbol:str='\x00'): ...
    
    @property
    def id(self) -> str: ...

    @property
    def productions(self) -> Set[Production]: ...
    
    @property
    def terminals(self) -> Set[Symbol]: ...
    
    @property
    def non_terminals(self) -> Set[Symbol]: ...
    
    @property
    def start_symbol(self) -> Symbol: ...

    def first(self,production:List[Symbol]) -> Set[Symbol]: ...

    def __getitem__(self,head:Symbol) -> ProductionsSet: ...
    
    def __setitem__(self,head:Symbol,productions:ProductionsSet) -> None: ...