from typing import Any, Dict


class Context:

    def __init__(self,global_scope:Dict[str,Any] = {},local_scope:Dict[str,Any] = {}) -> None: ...

    def add_to_scope(self,address:str,value:Any) -> None: ...
    
    def check_scope(self,address:str) -> bool: ...

    def get_value(self,address:str) -> Any: ...

    def clear(self) -> None: ...