from typing import Any, Dict, List
from .error import SemanticError,RuntimeError

class Context:

    def __init__(self,global_scope:Dict[str,Any] = {},local_scope:Dict[str,Any] = {}) -> None: ...

    @property
    def errors(self) -> List[SemanticError|RuntimeError]: ...

    def add_to_scope(self,address:str,value:Any) -> None: ...
    
    def check_scope(self,address:str) -> bool: ...

    def get_value(self,address:str) -> Any: ...

    def clear(self) -> None: ...

    def add_error(self,error:SemanticError) -> None: ...

    def add_runtime_error(self,error:RuntimeError) -> None: ...