from typing import List
from common.types import AST
from .error import SemanticError
from .context import Context

class ASTVisitor:
    
    def visit(self, ast:AST,context:Context) -> None: ...

class ASTChildrenSelector:

    def select_children(self, ast:AST,context:Context) -> List[AST]: ...

class TraversalStrategy:

    def __init__(self) -> None: ...

    def init(self, root:AST) -> None: ...

    def has_next(self) -> bool: ...
    
    def current(self,context:Context) -> AST: ...

    def reset(self) -> None: ...
    
    def _get_selector(self, ast:AST) -> ASTChildrenSelector: ...
    
    def add_selector(self, ast_type:type, selector:ASTChildrenSelector) -> None: ...

class ASTWalker:

    def __init__(self,context:Context,strategy:TraversalStrategy) -> None: ...

    def add_visitor(self,ast_type: type, visitor:ASTVisitor) -> None: ...

    def walk(self, ast:AST) -> None: ...