class Symbol:

    def __init__(self,symbol:str,is_terminal:bool = False,is_epsilon:bool = False): ...
    
    @property
    def symbol(self) -> str: ...
    
    @property
    def is_terminal(self) -> bool: ...
    
    @property
    def is_epsilon(self) -> bool: ...
    
    def __str__(self) -> str: ...
    
    def __repr__(self) -> str: ...

    def __eq__(self, other) -> bool: ...

    def __hash__(self) -> int: ...

class AST:
    '''
    Abstract Syntax Tree class
    '''
    def __init__(self,symbol:Symbol,line:int,column:int): ...
    
    @property
    def symbol(self) -> Symbol: ...
    
    @property
    def line(self) -> int: ...
    
    @property
    def column(self) -> int: ...
    
    def __str__(self) -> str: ...
    
    def __repr__(self) -> str: ...

class Token(AST):

    def __init__(self,text:str, type_:str, symbol: Symbol, line: int, column: int): ...    
    
    @property
    def text(self) -> str: ...
    
    @property
    def type(self) -> str: ...