from ..common.types import Token,LexicalError

class LexicalRule:
    
    def __init__(self,msg:str) -> None: ...

    def _check(self, text:str): ...

    def check(self,token:Token) -> LexicalError: ...