name: CI

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, windows-latest, macos-latest]
        python-version: [ "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Clean previous build (Linux/macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          python setup.py clean --all || true
          rm -rf build/*.so *.c
          rm -rf build*.egg-info
      
      - name: Clean previous build (Windows)
        if: runner.os == 'Windows'
        run: |
          python setup.py clean --all || true
          Remove-Item -Recurse -Force build -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force *.egg-info -ErrorAction SilentlyContinue
          Get-ChildItem -Recurse -Filter *.pyd | Remove-Item -Force -ErrorAction SilentlyContinue
        shell: pwsh
      
      - name: Build extensions
        run: |
          python setup.py build_ext --inplace --force


      - name: Run tests
        run: |
          python -m pytest tests
  
  build_wheels:
    name: Build wheels
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            archs: "auto64"
          - os: ubuntu-22.04
            archs: "auto64"
          - os: windows-latest
            archs: "auto64"
          - os: macos-latest
            archs: "x86_64 arm64"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install build dependencies
        uses: pypa/cibuildwheel@v3.3.1
        env:
          CIBW_BUILD: "cp312-* cp313-* cp314-*"
          CIBW_ARCHS: ${{ matrix.os }}
      
      - name: Save wheels
        uses: actions/upload-artifact@v4
        with:
          path: wheelhouse/*.whl